baseurl = "/"
theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "Min Cv"


[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "mariaines@outlook.dk"

	profilepic = "img/me.jpg"
	
	title = "Maria Ines"
	subtitle = "min CV"

	
	
#Menu
	
	
	[[params.navlinks]]
	name = "Om"
	url = "om"
    
    [[params.navlinks]]
	name = "Kontakt"
	url = "kontakt"
    
    [[params.navlinks]]
	name = "Portfolio"
	url = "portfolio"
	
	

